#!/bin/bash

if [[ "$#" -lt 1 ]]; then 
    echo "Usage: $0 <file> <file n>"
    exit 1
fi

for DIR in "$@"; do
    if [[ ! -e "$DIR" ]]; then
        echo "\"$DIR\" does not exist"
        continue
    fi

    if [[ "$DIR" == *.bak ]]; then
        mv -v "$DIR" "${DIR%.bak}"
    else
        mv -v "$DIR" "$DIR.bak"
    fi
done
